apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-root-ca-issuer
  namespace: kafka-cluster # Ensure this namespace exists
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-root-ca
  namespace: kafka-cluster
spec:
  isCA: true
  commonName: kafka-root-ca
  secretName: root-ca-secret # Secret storing the Root CA cert and key
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-root-ca-issuer
    kind: Issuer
    group: cert-manager.io
  duration: 43800h # 5 years
  renewBefore: 720h # 30 days
  usages:
    - digital signature
    - key encipherment
    - cert sign
