apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: kafka-cluster
data:
  zookeeper.properties.template: |
    # The Confluent entrypoint script will populate all other properties
    # from the ZOOKEEPER_* environment variables defined in the StatefulSet.
    # We only need to provide the properties that cannot be set via environment
    # variables, which is the list of quorum servers.
    server.1=zookeeper-0.zookeeper-headless.kafka-cluster.svc.cluster.local:2888:3888
    server.2=zookeeper-1.zookeeper-headless.kafka-cluster.svc.cluster.local:2888:3888
    server.3=zookeeper-2.zookeeper-headless.kafka-cluster.svc.cluster.local:2888:3888
