apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka-cluster
  labels:
    app: kafka
spec:
  ports:
    - name: internal-ssl # For inter-broker and internal clients
      port: 9093
    - name: controller # For KRaft controller communication (if used)
      port: 9094
  clusterIP: None # Headless service
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: kafka-cluster
  labels:
    app: kafka
spec:
  ports:
    - name: client-ssl # For external clients within the cluster
      port: 9093 # Matches one of the listener ports in server.properties
      targetPort: 9093
  selector:
    app: kafka
  type: ClusterIP
