apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: kafka-cluster
  labels:
    app: schema-registry
spec:
  ports:
    - name: https
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: schema-registry
  type: ClusterIP