apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-sa-read-secrets
  namespace: kafka-cluster # Ensure this matches your deployment namespace
subjects:
  - kind: ServiceAccount
    name: kafka-cluster-sa # Name of the ServiceAccount
    namespace: kafka-cluster
roleRef:
  kind: Role
  name: secret-reader-role # Name of the Role
  apiGroup: rbac.authorization.k8s.io
