apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
  namespace: kafka-cluster
type: Opaque
data:
  # Corresponds to __KAFKA_SERVER_KEYSTORE_PASSWORD__ in server.properties
  KAFKA_SERVER_KEYSTORE_PASSWORD: Y2hhbmdlaXRkZXY=
  # Corresponds to __KAFKA_SERVER_KEY_PASSWORD__ in server.properties
  KAFKA_SERVER_KEY_PASSWORD: Y2hhbmdlaXRkZXY=
  # Corresponds to __KAFKA_SERVER_TRUSTSTORE_PASSWORD__ in server.properties
  KAFKA_SERVER_TRUSTSTORE_PASSWORD: Y2hhbmdlaXRkZXY=
  # Corresponds to __KAFKA_ZKCLIENT_KEYSTORE_PASSWORD__ in server.properties
  KAFKA_ZKCLIENT_KEYSTORE_PASSWORD: Y2hhbmdlaXRkZXY=
  # Corresponds to __KAFKA_ZKCLIENT_TRUSTSTORE_PASSWORD__ in server.properties
  KAFKA_ZKCLIENT_TRUSTSTORE_PASSWORD: Y2hhbmdlaXRkZXY=
